### ISSUE TITLE
Compilation of light example fails with "ModuleNotFoundError: No module named 'lark'" (CON-252)

### ISSUE THREAD

**Issue by benjaminnestler** [espressif/esp-matter#196] opened 2023-02-02 08:37 UTC
Hi,

I've issues during compilation and linking of the examples!

Following steps to reproduce:
- fresh checked out repos `esp-matter`and `esp-idf`(v4.4.3)
- ./install.sh in both repos
- activatation of both environments (first esp-idf, second esp-matter)

```
cd esp-matter/examples/ligth
idf.py set-target esp32c3
idy.py build
```
fails with following message trace:

```
[46/729] ACTION //third_party/connectedhomeip/src/controller/data_model:data_model_codegen_codegen(//third_party/connectedhomeip/config/esp32/toolchain:esp32)
FAILED: gen/third_party/connectedhomeip/src/controller/data_model/app/PluginApplicationCallbacks.h gen/third_party/connectedhomeip/src/controller/data_model/app/callback-stub.cpp 
python ../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../../../../connectedhomeip/connectedhomeip/config/esp32/ --current-path ../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/src/controller/data_model --default-toolchain=//third_party/connectedhomeip/config/esp32/toolchain:esp32 --current-toolchain=//third_party/connectedhomeip/config/esp32/toolchain:esp32 --capture-output --python-dep-list-files gen/third_party/connectedhomeip/src/controller/data_model/data_model_codegen_codegen_metadata_path_list.txt -- ../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py --generator cpp-app --output-dir gen/third_party/connectedhomeip/src/controller/data_model --expected-outputs gen/third_party/connectedhomeip/src/controller/data_model/data_model_codegen.expected.outputs ../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/src/controller/data_model/controller-clusters.matter
Traceback (most recent call last):
  File "/media/psf/Home/VM_Workspaces/Ubuntu_Matter_ESP/esp/esp-matter/examples/light/build/esp-idf/chip/../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py", line 28, in <module>
    from idl.matter_idl_parser import CreateParser
  File "/media/psf/Home/VM_Workspaces/Ubuntu_Matter_ESP/esp/esp-matter/connectedhomeip/connectedhomeip/scripts/idl/matter_idl_parser.py", line 7, in <module>
    from lark import Lark
ModuleNotFoundError: No module named 'lark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/psf/Home/VM_Workspaces/Ubuntu_Matter_ESP/esp/esp-matter/examples/light/build/esp-idf/chip/../../../../../connectedhomeip/connectedhomeip/config/esp32/third_party/connectedhomeip/scripts/codegen.py", line 32, in <module>
    from idl.matter_idl_parser import CreateParser
  File "/media/psf/Home/VM_Workspaces/Ubuntu_Matter_ESP/esp/esp-matter/connectedhomeip/connectedhomeip/scripts/idl/matter_idl_parser.py", line 7, in <module>
    from lark import Lark
ModuleNotFoundError: No module named 'lark'
```
Full log is attached here [full_log_light_example.log](https://github.com/espressif/esp-matter/files/10566882/full_log_light_example.log)

Anybody an idea what happens?

**Comment by wqx6** [comment] 2023-02-02 09:15
Please following these steps to set up the python environment.
1. install and export IDF python environment by `cd esp-idf; ./install.sh; . ./export.sh`
2. install and export esp_matter requirement by `cd esp-matter; ./install.sh; . ./export.sh`

Then the error should be fixed.

**Comment by benjaminnestler** [comment] 2023-02-02 12:44
> Please following these steps to set up the python environment.
> 
>     1. install and export IDF python environment by `cd esp-idf; ./install.sh; . ./export.sh`
> 
>     2. install and export esp_matter requirement by `cd esp-matter; ./install.sh; . ./export.sh`
> 
> 
> Then the error should be fixed.

Sorry that's not the solution for my issue. Of course I activate the environments after installation process.

**Comment by igrr** [comment] 2023-02-02 13:25
Could you please capture the log of running `./install.sh` in esp-matter directory? This will help understand why the `lark` package didn't get installed.

(I got a similar issue recently, and in my case it was caused by the failure on ./install.sh due to a missing prerequisite. I haven't noticed that the script has failed and proceeded to the next step.)

**Comment by shubhamdp** [comment] 2023-02-02 14:38
Applications are built in idf python environment, so we have to run `source esp-idf/export.sh` before executing `esp-matter/install.sh`. This installs all the python dependencies in idf python environment.

**Comment by shubhamdp** [comment] 2023-02-02 14:39
[Documentation](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/developing.html#getting-the-repositories) does mention it but in getting esp-if section. It should have been into getting esp-matter section.

**Comment by benjaminnestler** [comment] 2023-02-02 21:45
> Applications are built in idf python environment, so we have to run `source esp-idf/export.sh` before executing `esp-matter/install.sh`. This installs all the python dependencies in idf python environment.

Okay, that could be my problem. I follow the instructions on the esp documentation site (you've linked it already).

And also as you said, the installation steps are not correct.

I will try it again tomorrow and give a feedback.

**Comment by MartinPArmstrong** [comment] 2023-02-03 01:21
I had the same error while compiling yesterday, i fixed the error by installing Lark manually.

`pip3 install lark`

**Comment by benjaminnestler** [comment] 2023-02-03 07:13
> Applications are built in idf python environment, so we have to run `source esp-idf/export.sh` before executing `esp-matter/install.sh`. This installs all the python dependencies in idf python environment.

That was definitely the solution for my issue!

**Closed** 2023-02-03 07:13 UTC
