### ISSUE TITLE
CHIP SDK Hangs randomly and device reboots due to watch dog timer timeout (CON-724)

### ISSUE THREAD

**Issue by aggaddam** [espressif/esp-matter#598] opened 2023-08-28 12:34 UTC
**Describe the bug**
CHIP SDK Hangs randomly and the device reboots due to watchdog timer timeout. The watchdog timeout period is set to 30 seconds (Which means the idle task didn't get a chance to execute itself within 30 seconds). Suspecting CHIP SDK is blocking CPU time and not releasing it back.

**Environment** :
- ESP-Matter Commit Id: 444f225576b47fa64e9f9313551b71c5c7f1c340
- ESP-IDF Commit Id:  e088c3766ba440e72268b458a68f27b6e7d63986
- SoC (eg: ESP32 or ESP32-C3): ESP32-C3
- Device Logs (Please attach the log file):  [esp32c3_device_crash.txt](https://github.com/espressif/esp-matter/files/12454434/esp32c3_device_crash.txt)
- Host Machine OS: Linux
- Commissioner app and versions if present: chip-tool
- Commissioner's logs if present:

**Any additional details**
...

**Comment by aggaddam** [comment] 2023-08-29 10:28
I got few more logs (Device side and Chip side logs) for the device crash during network pairing. 
Attached logs here for both device side and chiptool side

Chip Tool Log:
[chip_log1.txt](https://github.com/espressif/esp-matter/files/12463344/chip_log1.txt)

Esp32C3 Device Log:
[esp32c3_device_crash1.txt](https://github.com/espressif/esp-matter/files/12463350/esp32c3_device_crash1.txt)

**Comment by PSONALl** [comment] 2023-08-29 12:07
Can you use latest esp-matter commit 68e99de70266674ce172459136960bbb5c58dc0e ? I dont see the issue there

**Comment by PSONALl** [comment] 2023-08-30 05:49
> Esp32C3 Device Log: [esp32c3_device_crash1.txt](https://github.com/espressif/esp-matter/files/12463350/esp32c3_device_crash1.txt)

@aggaddam From these logs it looks like the crash is due to Matter resources being accessed from a non-Matter thread
For more details, you can check: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/faq.html#a1-11-chip-stack-locking-error-code-is-unsafe-racy

It is possible that your code is calling a matter API from a non-matter thread, Can you send a backtrace of your code before the crash happens

**Comment by aggaddam** [comment] 2023-08-30 09:28
> Can you use latest esp-matter commit [68e99de](https://github.com/espressif/esp-matter/commit/68e99de70266674ce172459136960bbb5c58dc0e) ? I dont see the issue there

I am seeing few warnings/errors when I create Room Air Conditioner device type with the latest ESP-Matter SDK (https://github.com/espressif/esp-matter/commit/68e99de70266674ce172459136960bbb5c58dc0e) that you pointed out. Is this expected or am I missing something here ?

Here are the errors/warnings

![Screenshot from 2023-08-30 14-55-54](https://github.com/espressif/esp-matter/assets/94963960/187958a6-5a24-4c33-8478-bb05a09c6fb2)

![Screenshot from 2023-08-30 14-58-40](https://github.com/espressif/esp-matter/assets/94963960/c02cba6d-716a-4944-abd9-3dfd3bf45922)

**Comment by aggaddam** [comment] 2023-08-30 11:44
> > Esp32C3 Device Log: [esp32c3_device_crash1.txt](https://github.com/espressif/esp-matter/files/12463350/esp32c3_device_crash1.txt)
> 
> @aggaddam From these logs it looks like the crash is due to Matter resources being accessed from a non-Matter thread For more details, you can check: https://docs.espressif.com/projects/esp-matter/en/latest/esp32/faq.html#a1-11-chip-stack-locking-error-code-is-unsafe-racy
> 
> It is possible that your code is calling a matter API from a non-matter thread, Can you send a backtrace of your code before the crash happens


I am calling matter API's with lock protection. Check this pseudo code
```

void matter_helperfcn_stop_commissioning_window(void)
{
    // Close the commission window
    lock::status_t lock_status = lock::chip_stack_lock(portMAX_DELAY);
    
    CommissioningWindowManager & commissionMgr = Server::GetInstance().GetCommissioningWindowManager();
    commissionMgr.CloseCommissioningWindow();
 
    if (lock::SUCCESS == lock_status)
    {
        lock::chip_stack_unlock();
    }    
}
```

**Comment by PSONALl** [comment] 2023-10-04 06:29
@aggaddam can you share a patch with your changes?

**Comment by aggaddam** [comment] 2023-10-04 07:37
@PSONALl  This issue is more frequently observed when log level is set to debug to instead of info.  Please try with the log level set to debug and then try matter commissioning for at least 5-10 times. 

This issue is also observed with log level info but occurrence is less compared to debug log level

**Comment by PSONALl** [comment] 2023-10-05 07:30
@aggaddam I tried to reproduce this issue by setting  log level is set to debug and tried commissioning more than 10 times but I am not able to reproduce the error
Please check if your changes are correct once

**Comment by aggaddam** [comment] 2023-10-12 08:13
@PSONALl Somehow, i am unable to reproduce the issue with examples code. I am trying to reproduce the issue by adding some application changes to the example code. Will share the patch If i am able to reproduce the issue

**Comment by dhrishi** [comment] 2023-11-23 09:15
I will close this now. Please re-open with the requested details if you encounter the issue

**Closed by dhrishi** 2023-11-23 09:15 UTC
