### ISSUE TITLE
Matter Light Switch Example on ESP32 (CON-885)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-matter#729] opened 2023-11-13 16:02 UTC
I am trying to use the Matter light switch example on ESP32-C6 (Matter over Thread) and I am able to commission it with the Apple Home app. But after commissioning it shows this error on home app and also does not let bind this switch to a light running on another esp32 board: 
![image](https://github.com/espressif/esp-matter/assets/9848328/4ac3da86-a54f-49ee-b53a-adf3025d4f0c)

Can you please tell me how to resolve this issue?

**Comment by bilalmalik76** [comment] 2023-11-13 18:20
Ok then I belive examples are already setup for both light app and light switch but I am not able to control light from light switch

**Comment by bilalmalik76** [comment] 2023-11-13 18:25
@jonsmirl but matter buttons can be bind with other matter devices and I see many commerical devices are available related to this for matter button.

**Comment by jonsmirl** [comment] 2023-11-13 18:30
You can use chip-tool to bind the light switch to the light bulb.

Who has shipped a Matter button?  Matter Buttons are not the same as a Light Switch. Matter Button is the esp-matter generic_switch example (not light_switch).  Matter Buttons don't need any setup, they just generate events. IOS supports them. I don't think Android does yet, but I have filed multiple bugs on them about implementing support.

**Comment by jonsmirl** [comment] 2023-11-13 18:57
The button in the video is the same as the esp-matter/generic switch example.

**Comment by bilalmalik76** [comment] 2023-11-13 19:13
I am getting this error with esp-matter/generic switch example:
![image](https://github.com/espressif/esp-matter/assets/9848328/1fcc8242-be62-42a9-a070-a757e8e17aed)

**Comment by jonsmirl** [comment] 2023-11-13 21:05
Looks like something having to do with Thread. It should work on Wifi.

**Comment by bilalmalik76** [comment] 2023-11-14 03:12
but I need to use Matter over Thread

**Comment by jonsmirl** [comment] 2023-11-14 03:16
Espressif employees will need to help you, I am not using Thread in my products.

**Comment by bilalmalik76** [comment] 2023-11-14 03:19
@jonsmirl Thanks for your help. Let's wait for the Espressif employees response.

**Comment by dhrishi** [comment] 2023-11-14 13:23
I am closing this issue as Light Switch is currently not supported in the ecosystem. And the other issue is tracked in #731

**Closed by dhrishi** 2023-11-14 13:23 UTC

**Comment by bilalmalik76** [comment] 2023-11-18 09:34
@dhrishi If I use matter examples in Matter rainmaker, will it work? I mean is raink maker app support light switch?

**Comment by bilalmalik76** [comment] 2023-11-18 09:48
@dhrishi how this device is using Apple Home app, if matter light switch is not supported in ecosystem?
https://www.avatarcontrols.com/products/matter-over-wifi-smart-light-switch-eu-version

**Comment by jonsmirl** [comment] 2023-11-18 12:19
The linked device is not a light switch, it is a Matter light bulb.  All of the Matter 'light switches' currently on the market are just Matter light bulbs with a local hardware switch.  

AFAIK no one is shipping an actual Matter light switch. Matter light switches let you set up three way (or N-way) control of the bulbs,

**Comment by bilalmalik76** [comment] 2023-11-18 13:41
@jonsmirl  it says matter light switch
![Uploading image.png…]()

**Comment by jonsmirl** [comment] 2023-11-18 14:01
https://www.avatarcontrols.com/products/matter-over-wifi-smart-light-switch-eu-version
That product is implementing a Matter light bulb. To reproduce this product, use the esp_matter example 'light' (not 'light_switch). The wall unit is declaring itself to be a Matter light bulb. Then the wires run from the wall unit to the dumb light bulb. The physical switch on the wall unit is not accessible to Apple Home. If you buy one of the units and add it to Apple Home this will be obvious. It says 'light switch' in the marketing description, but that is not what the device is actually doing.

The Matter device 'light switch' is much more complex and it is used to make N-way lighting setups. That can not be done with the Apple/Google apps. You have to have a proprietary app to set it up. The esp-matter light_switch example explains how to set things up using chip-tool.  Google/Apple Home are never going to directly support 'light switch'.

**Comment by bilalmalik76** [comment] 2023-11-18 17:48
@jonsmirl did you try this app from espressif: https://apps.apple.com/in/app/espressif-matter/id1604739172?platform=iphone
looks like it has support for light switch and gives binding option also.

**Comment by jonsmirl** [comment] 2023-11-18 17:52
That is an example of a custom app to set up the bindings.  Do note, the Matter Light Switch device does not contain a Light.

**Comment by bilalmalik76** [comment] 2023-11-18 18:23
I just tried this app by installing on my iPhone but not able to commission any device either matter over Wi-Fi or Matter over Thread. @dhrishi is Expressif Mattter app still works?

**Comment by bilalmalik76** [comment] 2023-11-19 10:09
@jonsmirl What if I want to control led brightness on another device, is it possible to do with light example?

**Comment by jonsmirl** [comment] 2023-11-19 13:04
You need to add support for the LevelControl client cluster to the light_switch example.  But to do that you will need to add more physical buttons to the dev board. One for up and down. Adding LevelControl turns it into a DimmerSwitch.   You can even make an ExtendedColorSwitch but that will need even more UI capability like a touch screen.

**Comment by mgoeller** [comment] 2023-12-10 19:02
> Google/Apple Home are never going to directly support 'light switch'.

What makes you think so? I think the Apple, Google & Co Home Apps will allow to create bindings at some point in the future...

**Comment by jonsmirl** [comment] 2023-12-10 19:23
Maybe, but they don't view that as part of their business currently. Could be years away. Right now it is considered a 'vendor' problem.

**Comment by mgoeller** [comment] 2023-12-10 19:26
I think they will introduce an option soon with a similar GUI as "binding" a 'matter button' (/homekit programmable switch) to an accessory / scene.

**Comment by jonsmirl** [comment] 2023-12-10 19:39
Also, generic buttons (ie Matter Buttons) are never bound to anything. The only thing they do is send messages to a controller like Apple/Google/Amazon. You are always free to script those button events anyway you want. How those scripts are implemented is not part of Matter.

That is very different than binding a Matter Light Switch to a Matter Light Bulb. That type of binding works without the controller being involved. This is the type of binding not coming anytime soon to Google/Apple/Amazon.

**Comment by mgoeller** [comment] 2023-12-11 11:13
I know that the "programmable switch" is totally different than a matter binding, thats why I said "with a similar GUI". But I understand the cross fabric problem now...

**Comment by jonsmirl** [comment] 2023-12-11 15:24
Under Zigbee there was only one fabric. With Matter there is one for every vendor. Now use a vendor app to configure a bunch of fancy special effect lighting scenes and you have a problem -- those scenes are on the vendor fabric and google/apple/amazon can't trigger them.  Zigbee doesn't have this issue. Google/apple/amazon don't want to build these specialized UIs since they aren't in the lighting business.  Matter needs to come up with a cross fabric solution to triggering these things.
